services:
  web:
    image: swaggerapi/swagger-ui
    ports:
      - "80:8080"
    environment:
      - SWAGGER_JSON=/openapi-schema/apidocs.swagger.json
    volumes:
      - ./gen/openapi-schema:/openapi-schema
