/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Sample API
 * OpenAPI spec version: 0.0.0
 */

export interface ProtobufAny {
  "@type"?: string;
  [key: string]: { [key: string]: any };
}
