/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Sample API
 * OpenAPI spec version: 0.0.0
 */
import type { ProtobufAny } from "./protobufAny";

export interface RpcStatus {
  code?: number;
  details?: ProtobufAny[];
  message?: string;
}
