/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Sample API
 * OpenAPI spec version: 0.0.0
 */
import type { V1Post } from "./v1Post";

export interface V1PostServiceGetResponse {
  row: V1Post;
}
