/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Sample API
 * OpenAPI spec version: 0.0.0
 */

export interface V1Post {
  createdAt: string;
  id: number;
  name: string;
  title: string;
}
