/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/comment/get": {
    post: operations["CommentService_Get"];
  };
  "/v1/post/get": {
    post: operations["PostService_Get"];
  };
  "/v1/post/search": {
    post: operations["PostService_Search"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @example {
     *   "@type": "@type"
     * }
     */
    protobufAny: {
      "@type"?: string;
      [key: string]: Record<string, never> | undefined;
    };
    /**
     * @example {
     *   "code": 0,
     *   "details": [
     *     {
     *       "@type": "@type"
     *     },
     *     {
     *       "@type": "@type"
     *     }
     *   ],
     *   "message": "message"
     * }
     */
    rpcStatus: {
      /** Format: int32 */
      code?: number;
      message?: string;
      details?: components["schemas"]["protobufAny"][];
    };
    v1CommentServiceGetRequest: {
      /** Format: int32 */
      id?: number;
    };
    /**
     * @example {
     *   "comment": "comment"
     * }
     */
    v1CommentServiceGetResponse: {
      comment?: string;
    };
    /**
     * @example {
     *   "createdAt": "createdAt",
     *   "name": "name",
     *   "id": 0,
     *   "title": "title"
     * }
     */
    v1Post: {
      /** Format: int32 */
      id?: number;
      name?: string;
      title?: string;
      createdAt?: string;
    };
    v1PostServiceGetRequest: {
      /** Format: int32 */
      id?: number;
    };
    /**
     * @example {
     *   "row": {
     *     "createdAt": "createdAt",
     *     "name": "name",
     *     "id": 0,
     *     "title": "title"
     *   }
     * }
     */
    v1PostServiceGetResponse: {
      row?: components["schemas"]["v1Post"];
    };
    v1PostServiceSearchRequest: {
      keyword?: string;
      start?: string;
      end?: string;
    };
    /**
     * @example {
     *   "rows": [
     *     {
     *       "createdAt": "createdAt",
     *       "name": "name",
     *       "id": 0,
     *       "title": "title"
     *     },
     *     {
     *       "createdAt": "createdAt",
     *       "name": "name",
     *       "id": 0,
     *       "title": "title"
     *     }
     *   ]
     * }
     */
    v1PostServiceSearchResponse: {
      rows?: components["schemas"]["v1Post"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  CommentService_Get: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["v1CommentServiceGetRequest"];
      };
    };
    responses: {
      /** @description A successful response. */
      200: {
        content: {
          "application/json": components["schemas"]["v1CommentServiceGetResponse"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        content: {
          "application/json": components["schemas"]["rpcStatus"];
        };
      };
    };
  };
  PostService_Get: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["v1PostServiceGetRequest"];
      };
    };
    responses: {
      /** @description A successful response. */
      200: {
        content: {
          "application/json": components["schemas"]["v1PostServiceGetResponse"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        content: {
          "application/json": components["schemas"]["rpcStatus"];
        };
      };
    };
  };
  PostService_Search: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["v1PostServiceSearchRequest"];
      };
    };
    responses: {
      /** @description A successful response. */
      200: {
        content: {
          "application/json": components["schemas"]["v1PostServiceSearchResponse"];
        };
      };
      /** @description An unexpected error response. */
      default: {
        content: {
          "application/json": components["schemas"]["rpcStatus"];
        };
      };
    };
  };
}
