/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/comment/get": {
    post: operations["CommentService_Get"];
  };
  "/v1/post/get": {
    post: operations["PostService_Get"];
  };
  "/v1/post/search": {
    post: operations["PostService_Search"];
  };
}

export interface definitions {
  protobufAny: {
    "@type"?: string;
  } & { [key: string]: unknown };
  rpcStatus: {
    /** Format: int32 */
    code?: number;
    message?: string;
    details?: definitions["protobufAny"][];
  };
  v1CommentServiceGetRequest: {
    /** Format: int32 */
    id?: number;
  };
  v1CommentServiceGetResponse: {
    comment?: string;
  };
  v1Post: {
    /** Format: int32 */
    id?: number;
    name?: string;
    title?: string;
    createdAt?: string;
  };
  v1PostServiceGetRequest: {
    /** Format: int32 */
    id?: number;
  };
  v1PostServiceGetResponse: {
    row?: definitions["v1Post"];
  };
  v1PostServiceSearchRequest: {
    keyword?: string;
    start?: string;
    end?: string;
  };
  v1PostServiceSearchResponse: {
    rows?: definitions["v1Post"][];
  };
}

export interface operations {
  CommentService_Get: {
    parameters: {
      body: {
        body: definitions["v1CommentServiceGetRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1CommentServiceGetResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  PostService_Get: {
    parameters: {
      body: {
        body: definitions["v1PostServiceGetRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1PostServiceGetResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  PostService_Search: {
    parameters: {
      body: {
        body: definitions["v1PostServiceSearchRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1PostServiceSearchResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
}

export interface external {}
