import createClient from "openapi-fetch";
import type { paths } from "./types/schema"; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: "https://myapi.dev/v1/" });

(async () => {
  const { data } = await client.POST("/v1/post/get", {
    body: { id: 1 },
  });
})();
